services:
  - type: web
    name: multi-store-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: APP_NAME
        value: MultiStore
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:LXdOy063qHz+PAOOkiJUFbGWtb9JNH6nNcYui7gmLDQ=
      - key: APP_URL
        value: https://multi-store-backend.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-snowy-silence-at80u7ih.c-9.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432;options=endpoint=ep-snowy-silence-at80u7ih"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_HARLfqMQU5i1
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
